# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b79ad4828578427759dc252ac2fbd4bb4c909991929c5d194529a75186808fbcd6805508469f864813d5543e6ac3fd428fd4270ee6e6e3e5a0ab84eb0f2cfffa

test:
  secret_key_base: b556c6e40dff89c3f05bb905bd166868eb829fc5d954f7b0fc8a45e08b679b4a45f2c219f0026dee017fb29258b0d3ea1db4019051ae7390b2518058559c9220

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
